global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: minio-node1
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: 
      - 'minio1:9000'
      - 'minio2:9000'
      - 'minio3:9000'
      - 'minio4:9000'
      
scrape_configs:
    - job_name: minio-job
      metrics_path: /minio/v2/metrics/cluster
      scheme: https
      static_configs:
      - targets: ['nginx:443']
